spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/project-service/**

        - id: tag-service
          uri: lb://TAG-SERVICE
          predicates:
            - Path=/tag-service/**

        - id: subscription-service
          uri: lb://SUBSCRIPTION-SERVICE
          predicates:
            - Path=/subscription-service/**

        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account-service/**
#
#  application:
#    name: API-GATEWAY
#
#server:
#  port: 8765
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/