spring:
  cloud:
    gateway:
      routes:
        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/project-service/**
          filters:
            - AuthenticationFilter

        - id: tag-service
          uri: lb://TAG-SERVICE
          predicates:
            - Path=/tag-service/**
          filters:
            - AuthenticationFilter

        - id: subscription-service
          uri: lb://SUBSCRIPTION-SERVICE
          predicates:
            - Path=/subscription-service/**
          filters:
            - AuthenticationFilter

        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account-service/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
#
#  application:
#    name: API-GATEWAY
#
#server:
#  port: 8765
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/