server:
  port: 8765

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: PROJECT-SERVICE
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/project-service/**

        - id: TAG-SERVICE
          uri: lb://TAG-SERVICE
          predicates:
            - Path=/tag-service/**

        - id: SUBSCRIPTION-SERVICE
          uri: lb://SUBSCRIPTION-SERVICE
          predicates:
            - Path=/subscription-service/**

        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account-service/**

        - id: eureka
          uri: lb://eureka
          predicates:
            - Path=/eureka/**

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
#      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://mappy-eureka:8761/eureka